package constants

var CountryNamesEnglish = []string{
	"Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica (the territory South of 60 deg S)", "Antigua and Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
	"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island (Bouvetoya)", "Brazil", "British Indian Ocean Territory (Chagos Archipelago)", "British Virgin Islands", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi",
	"Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo", "Congo", "Cook Islands", "Costa Rica", "Cote d\"Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic",
	"Denmark", "Djibouti", "Dominica", "Dominican Republic",
	"Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia",
	"Faroe Islands", "Falkland Islands (Malvinas)", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories",
	"Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana",
	"Haiti", "Heard Island and McDonald Islands", "Holy See (Vatican City State)", "Honduras", "Hong Kong", "Hungary",
	"Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy",
	"Jamaica", "Japan", "Jersey", "Jordan",
	"Kazakhstan", "Kenya", "Kiribati", "Korea", "Korea", "Kuwait", "Kyrgyz Republic",
	"Lao People\"s Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya", "Liechtenstein", "Lithuania", "Luxembourg",
	"Macao", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar",
	"Namibia", "Nauru", "Nepal", "Netherlands Antilles", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway",
	"Oman",
	"Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico",
	"Qatar",
	"Reunion", "Romania", "Russian Federation", "Rwanda",
	"Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia", "Saint Martin", "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia (Slovak Republic)", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard & Jan Mayen Islands", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
	"Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands", "Tuvalu",
	"Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States of America", "United States Minor Outlying Islands", "United States Virgin Islands", "Uruguay", "Uzbekistan",
	"Vanuatu", "Venezuela", "Vietnam",
	"Wallis and Futuna", "Western Sahara",
	"Yemen",
	"Zambia", "Zimbabwe",
}

var LoremWordList = []string{
	"alias", "consequatur", "aut", "perferendis", "sit", "voluptatem",
	"accusantium", "doloremque", "aperiam", "eaque", "ipsa", "quae", "ab",
	"illo", "inventore", "veritatis", "et", "quasi", "architecto",
	"beatae", "vitae", "dicta", "sunt", "explicabo", "aspernatur", "aut",
	"odit", "aut", "fugit", "sed", "quia", "consequuntur", "magni",
	"dolores", "eos", "qui", "ratione", "voluptatem", "sequi", "nesciunt",
	"neque", "dolorem", "ipsum", "quia", "dolor", "sit", "amet",
	"consectetur", "adipisci", "velit", "sed", "quia", "non", "numquam",
	"eius", "modi", "tempora", "incidunt", "ut", "labore", "et", "dolore",
	"magnam", "aliquam", "quaerat", "voluptatem", "ut", "enim", "ad",
	"minima", "veniam", "quis", "nostrum", "exercitationem", "ullam",
	"corporis", "nemo", "enim", "ipsam", "voluptatem", "quia", "voluptas",
	"sit", "suscipit", "laboriosam", "nisi", "ut", "aliquid", "ex", "ea",
	"commodi", "consequatur", "quis", "autem", "vel", "eum", "iure",
	"reprehenderit", "qui", "in", "ea", "voluptate", "velit", "esse",
	"quam", "nihil", "molestiae", "et", "iusto", "odio", "dignissimos",
	"ducimus", "qui", "blanditiis", "praesentium", "laudantium", "totam",
	"rem", "voluptatum", "deleniti", "atque", "corrupti", "quos",
	"dolores", "et", "quas", "molestias", "excepturi", "sint",
	"occaecati", "cupiditate", "non", "provident", "sed", "ut",
	"perspiciatis", "unde", "omnis", "iste", "natus", "error",
	"similique", "sunt", "in", "culpa", "qui", "officia", "deserunt",
	"mollitia", "animi", "id", "est", "laborum", "et", "dolorum", "fuga",
	"et", "harum", "quidem", "rerum", "facilis", "est", "et", "expedita",
	"distinctio", "nam", "libero", "tempore", "cum", "soluta", "nobis",
	"est", "eligendi", "optio", "cumque", "nihil", "impedit", "quo",
	"porro", "quisquam", "est", "qui", "minus", "id", "quod", "maxime",
	"placeat", "facere", "possimus", "omnis", "voluptas", "assumenda",
	"est", "omnis", "dolor", "repellendus", "temporibus", "autem",
	"quibusdam", "et", "aut", "consequatur", "vel", "illum", "qui",
	"dolorem", "eum", "fugiat", "quo", "voluptas", "nulla", "pariatur",
	"at", "vero", "eos", "et", "accusamus", "officiis", "debitis", "aut",
	"rerum", "necessitatibus", "saepe", "eveniet", "ut", "et",
	"voluptates", "repudiandae", "sint", "et", "molestiae", "non",
	"recusandae", "itaque", "earum", "rerum", "hic", "tenetur", "a",
	"sapiente", "delectus", "ut", "aut", "reiciendis", "voluptatibus",
	"maiores", "doloribus", "asperiores", "repellat",
}

// CurrencyCode See https://en.wikipedia.org/wiki/ISO_4217
var CurrencyCode = []string{
	"AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN",
	"BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL",
	"BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHF", "CLP", "CNY",
	"COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD",
	"EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GHS", "GIP",
	"GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS",
	"INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR",
	"KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD",
	"LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU",
	"MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK",
	"NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG",
	"QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK",
	"SGD", "SHP", "SLL", "SOS", "SRD", "SSP", "STN", "SYP", "SZL", "THB",
	"TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX",
	"USD", "UYU", "UZS", "VES", "VND", "VUV", "WST", "XAF", "XCD", "XOF",
	"XPF", "YER", "ZAR", "ZMW",
}

// LocaleData
// See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
var LocaleData = []string{
	"aa_DJ", "aa_ER", "aa_ET",
	"af_NA", "af_ZA", "ak_GH",
	"am_ET", "ar_AE", "ar_BH", "ar_DZ",
	"ar_EG", "ar_IQ", "ar_JO", "ar_KW", "ar_LB",
	"ar_LY", "ar_MA", "ar_OM", "ar_QA", "ar_SA",
	"ar_SD", "ar_SY", "ar_TN", "ar_YE",
	"as_IN", "az_AZ", "be_BY",
	"bg_BG", "bn_BD", "bn_IN",
	"bo_CN", "bo_IN", "bs_BA",
	"byn_ER", "ca_ES",
	"cch_NG", "cs_CZ",
	"cy_GB", "da_DK", "de_AT",
	"de_BE", "de_CH", "de_DE", "de_LI", "de_LU",
	"dv_MV", "dz_BT",
	"ee_GH", "ee_TG", "el_CY", "el_GR",
	"en_AS", "en_AU", "en_BE", "en_BW",
	"en_BZ", "en_CA", "en_GB", "en_GU", "en_HK",
	"en_IE", "en_IN", "en_JM", "en_MH", "en_MP",
	"en_MT", "en_NA", "en_NZ", "en_PH", "en_PK",
	"en_SG", "en_TT", "en_UM", "en_US", "en_VI",
	"en_ZA", "en_ZW", "es_AR",
	"es_BO", "es_CL", "es_CO", "es_CR", "es_DO",
	"es_EC", "es_ES", "es_GT", "es_HN", "es_MX",
	"es_NI", "es_PA", "es_PE", "es_PR", "es_PY",
	"es_SV", "es_US", "es_UY", "es_VE",
	"et_EE", "eu_ES", "fa_AF",
	"fa_IR", "fi_FI", "fil_PH",
	"fo_FO", "fr_BE", "fr_CA",
	"fr_CH", "fr_FR", "fr_LU", "fr_MC", "fr_SN",
	"fur_IT", "ga_IE",
	"gaa_GH", "gez_ER", "gez_ET",
	"gl_ES", "gsw_CH", "gu_IN",
	"gv_GB", "ha_GH", "ha_NE",
	"ha_NG", "ha_SD", "haw_US",
	"he_IL", "hi_IN", "hr_HR",
	"hu_HU", "hy_AM",
	"id_ID", "ig_NG",
	"ii_CN", "is_IS",
	"it_CH", "it_IT",
	"ja_JP", "ka_GE", "kaj_NG",
	"kam_KE", "kcg_NG",
	"kfo_CI", "kk_KZ", "kl_GL",
	"km_KH", "kn_IN",
	"ko_KR", "kok_IN", "kpe_GN",
	"kpe_LR", "ku_IQ", "ku_IR", "ku_SY",
	"ku_TR", "kw_GB", "ky_KG",
	"ln_CD", "ln_CG", "lo_LA",
	"lt_LT", "lv_LV",
	"mk_MK", "ml_IN", "mn_CN",
	"mn_MN", "mr_IN",
	"ms_BN", "ms_MY", "mt_MT",
	"my_MM", "nb_NO", "nds_DE",
	"ne_IN", "ne_NP", "nl_BE",
	"nl_NL", "nn_NO",
	"nr_ZA", "nso_ZA", "ny_MW",
	"oc_FR", "om_ET", "om_KE",
	"or_IN", "pa_IN", "pa_PK",
	"pl_PL", "ps_AF",
	"pt_BR", "pt_PT", "ro_MD", "ro_RO",
	"ru_RU", "ru_UA", "rw_RW",
	"sa_IN", "se_FI", "se_NO",
	"sh_BA", "sh_CS", "sh_YU",
	"si_LK", "sid_ET", "sk_SK",
	"sl_SI", "so_DJ", "so_ET",
	"so_KE", "so_SO", "sq_AL",
	"sr_BA", "sr_CS", "sr_ME", "sr_RS", "sr_YU",
	"ss_SZ", "ss_ZA", "st_LS",
	"st_ZA", "sv_FI", "sv_SE",
	"sw_KE", "sw_TZ", "syr_SY",
	"ta_IN", "te_IN", "tg_TJ",
	"th_TH", "ti_ER", "ti_ET",
	"tig_ER", "tn_ZA",
	"to_TO", "tr_TR",
	"trv_TW", "ts_ZA", "tt_RU",
	"ug_CN", "uk_UA",
	"ur_IN", "ur_PK", "uz_AF", "uz_UZ",
	"ve_ZA", "vi_VN",
	"wal_ET", "wo_SN", "xh_ZA",
	"yo_NG", "zh_CN", "zh_HK",
	"zh_MO", "zh_SG", "zh_TW", "zu_ZA",
}

// CountryISOAlpha3
// See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3
var CountryISOAlpha3 = []string{
	"ABW", "AFG", "AGO", "AIA", "ALA", "ALB", "AND", "ARE", "ARG", "ARM",
	"ASM", "ATA", "ATF", "ATG", "AUS", "AUT", "AZE", "BDI", "BEL", "BEN",
	"BES", "BFA", "BGD", "BGR", "BHR", "BHS", "BIH", "BLM", "BLR", "BLZ",
	"BMU", "BOL", "BRA", "BRB", "BRN", "BTN", "BVT", "BWA", "CAF", "CAN",
	"CCK", "CHE", "CHL", "CHN", "CIV", "CMR", "COD", "COG", "COK", "COL",
	"COM", "CPV", "CRI", "CUB", "CUW", "CXR", "CYM", "CYP", "CZE", "DEU",
	"DJI", "DMA", "DNK", "DOM", "DZA", "ECU", "EGY", "ERI", "ESH", "ESP",
	"EST", "ETH", "FIN", "FJI", "FLK", "FRA", "FRO", "FSM", "GAB", "GBR",
	"GEO", "GGY", "GHA", "GIB", "GIN", "GLP", "GMB", "GNB", "GNQ", "GRC",
	"GRD", "GRL", "GTM", "GUF", "GUM", "GUY", "HKG", "HMD", "HND", "HRV",
	"HTI", "HUN", "IDN", "IMN", "IND", "IOT", "IRL", "IRN", "IRQ", "ISL",
	"ISR", "ITA", "JAM", "JEY", "JOR", "JPN", "KAZ", "KEN", "KGZ", "KHM",
	"KIR", "KNA", "KOR", "KWT", "LAO", "LBN", "LBR", "LBY", "LCA", "LIE",
	"LKA", "LSO", "LTU", "LUX", "LVA", "MAC", "MAF", "MAR", "MCO", "MDA",
	"MDG", "MDV", "MEX", "MHL", "MKD", "MLI", "MLT", "MMR", "MNE", "MNG",
	"MNP", "MOZ", "MRT", "MSR", "MTQ", "MUS", "MWI", "MYS", "MYT", "NAM",
	"NCL", "NER", "NFK", "NGA", "NIC", "NIU", "NLD", "NOR", "NPL", "NRU",
	"NZL", "OMN", "PAK", "PAN", "PCN", "PER", "PHL", "PLW", "PNG", "POL",
	"PRI", "PRK", "PRT", "PRY", "PSE", "PYF", "QAT", "REU", "ROU", "RUS",
	"RWA", "SAU", "SDN", "SEN", "SGP", "SGS", "SHN", "SJM", "SLB", "SLE",
	"SLV", "SMR", "SOM", "SPM", "SRB", "SSD", "STP", "SUR", "SVK", "SVN",
	"SWE", "SWZ", "SXM", "SYC", "SYR", "TCA", "TCD", "TGO", "THA", "TJK",
	"TKL", "TKM", "TLS", "TON", "TTO", "TUN", "TUR", "TUV", "TWN", "TZA",
	"UGA", "UKR", "UMI", "URY", "USA", "UZB", "VAT", "VCT", "VEN", "VGB",
	"VIR", "VNM", "VUT", "WLF", "WSM", "YEM", "ZAF", "ZMB", "ZWE",
}

// CountryCodes
// see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
var CountryCodes = []string{
	"AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR",
	"AS", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE",
	"BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ",
	"BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CC", "CD", "CF",
	"CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU",
	"CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO",
	"DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "FI", "FJ",
	"FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF", "GG",
	"GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT",
	"GU", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE",
	"IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM",
	"JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR",
	"KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS",
	"LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG",
	"MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS",
	"MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE",
	"NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM",
	"PA", "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR",
	"PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW",
	"SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK",
	"SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY",
	"SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM",
	"TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM",
	"US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU",
	"WF", "WS", "YE", "YT", "ZA", "ZM", "ZW",
}

// LanguageCodes
// See https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
var LanguageCodes = []string{
	"aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av",
	"ay", "az", "ba", "be", "bg", "bh", "bi", "bm", "bn", "bo",
	"br", "bs", "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv",
	"cy", "da", "de", "dv", "dz", "ee", "el", "en", "eo", "es",
	"et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy", "ga",
	"gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr",
	"ht", "hu", "hy", "hz", "ia", "id", "ie", "ig", "ii", "ik",
	"io", "is", "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj",
	"kk", "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw",
	"ky", "la", "lb", "lg", "li", "ln", "lo", "lt", "lu", "lv",
	"mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my",
	"na", "nb", "nd", "ne", "ng", "nl", "nn", "no", "nr", "nv",
	"ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl", "ps",
	"pt", "qu", "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd",
	"se", "sg", "si", "sk", "sl", "sm", "sn", "so", "sq", "sr",
	"ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti",
	"tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug",
	"uk", "ur", "uz", "ve", "vi", "vo", "wa", "wo", "xh", "yi",
	"yo", "za", "zh", "zu",
}

// Emojis
// See https://en.wikipedia.org/wiki/Emoji#Unicode_blocks
var Emojis = []string{
	"\U0001F600", "\U0001F601", "\U0001F602", "\U0001F603",
	"\U0001F604", "\U0001F605", "\U0001F606", "\U0001F607",
	"\U0001F608", "\U0001F609", "\U0001F60A", "\U0001F60B",
	"\U0001F60C", "\U0001F60D", "\U0001F60E", "\U0001F60F",
	"\U0001F610", "\U0001F611", "\U0001F612", "\U0001F613",
	"\U0001F614", "\U0001F615", "\U0001F616", "\U0001F617",
	"\U0001F618", "\U0001F619", "\U0001F61A", "\U0001F61B",
	"\U0001F61C", "\U0001F61D", "\U0001F61E", "\U0001F61F",
	"\U0001F620", "\U0001F621", "\U0001F622", "\U0001F623",
	"\U0001F624", "\U0001F625", "\U0001F626", "\U0001F627",
	"\U0001F628", "\U0001F629", "\U0001F62A", "\U0001F62B",
	"\U0001F62C", "\U0001F62D", "\U0001F62E", "\U0001F62F",
	"\U0001F630", "\U0001F631", "\U0001F632", "\U0001F633",
	"\U0001F634", "\U0001F635", "\U0001F636", "\U0001F637",
}

var AllColorNames = []string{
	"AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine",
	"Azure", "Beige", "Bisque", "Black", "BlanchedAlmond",
	"Blue", "BlueViolet", "Brown", "BurlyWood", "CadetBlue",
	"Chartreuse", "Chocolate", "Coral", "CornflowerBlue",
	"Cornsilk", "Crimson", "Cyan", "DarkBlue", "DarkCyan",
	"DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki",
	"DarkMagenta", "DarkOliveGreen", "Darkorange", "DarkOrchid",
	"DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue",
	"DarkSlateGray", "DarkTurquoise", "DarkViolet", "DeepPink",
	"DeepSkyBlue", "DimGray", "DimGrey", "DodgerBlue", "FireBrick",
	"FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite",
	"Gold", "GoldenRod", "Gray", "Green", "GreenYellow", "HoneyDew",
	"HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender",
	"LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral",
	"LightCyan", "LightGoldenRodYellow", "LightGray", "LightGreen", "LightPink",
	"LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSteelBlue",
	"LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine",
	"MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue",
	"MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue",
	"MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive",
	"OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen",
	"PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum",
	"PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon",
	"SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue",
	"SlateGray", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato",
	"Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen",
}

var SafeColorNames = []string{
	"black", "maroon", "green", "navy", "olive",
	"purple", "teal", "lime", "blue", "silver",
	"gray", "yellow", "fuchsia", "aqua", "white",
}

var BloodTypes = []string{
	"A", "AB", "B", "O",
}
var BloodRhFactors = []string{
	"+", "-",
}
